name: ai-configurable-mvp
services:
- name: api
  source_dir: /
  github:
    repo: https://github.com/Emak-star/ai-mvp-backend
    branch: main
  run_command: uvicorn main:app --host=0.0.0.0 --port=$PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: PORT
    value: "8080"
  - key: SUPABASE_URL
    value: https://mdpurtoksnwmpknkxtic.supabase.co
  - key: SUPABASE_SERVICE_KEY
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kdXB1cnRva3NubndtcGtucmt4aWNjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMTI3OTM0MywiZXhwIjoyMDQ2ODUzMzQzfQ.18b30F02qXkZtYl2xG4cV1o-60zP6qT948jFg67811Q
  - key: OPENAI_API_KEY
    value: sk-proj-1234567890
  - key: DEBUG
    value: "False"
  - key: HOST
    value: "0.0.0.0"
